### ISSUE TITLE
Graph addition of strings test failed

### ISSUE THREAD

**Issue by ljulliar** [somaticio/tensorflow.rb#88]
Hi,
First of ll congratulations for the fantastic work you have done with this Ruby interface to TensorFlow.
I just wanted to report I got today. A couple of days ago I went through the installation process step by step and it worked like a charm including the test suite at the end invoked through the "bundle exec rake test" command.
Today I decided I had enough with those warnings from the TensorFlow library telling me that I wasn't using all the nice SIMD instruction set available on my CPU and I decided to recompile TF with the following options:

> bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.1 --copt=-msse4.2 //tensorflow:libtensorflow.so

Everything went well except that after rebuilding the Ruvy extension all test passed successfully except this one below. Any idea why this is happening ?

```
Failures:

  1) Graph Addition of strings
     Failure/Error: expect(out_tensor[0]).to eq('TensorflowRuby')

       expected: "TensorflowRuby"
            got: "TensorflowRubylowRuby"

       (compared using ==)
     # ./spec/graph_spec.rb:29:in `block (2 levels) in <top (required)>'

Finished in 0.08098 seconds (files took 0.21106 seconds to load)
70 examples, 1 failure

Failed examples:
rspec ./spec/graph_spec.rb:21 # Graph Addition of strings

```

**Comment by Arafatk** [comment]
@ljulliar Thanks a lot for your query, warnings are something that bothered me for some time but I ignored them because of [this](https://github.com/tensorflow/tensorflow/issues/7778).     
I am really sorry that I couldn't reply to you earlier,  as I recently immigrated to Canada from India and it took me some time to get set up.      
I have been looking at this and trying to replicate this.    
I think this is most likely an internal issue and most likely I won't be able to resolve it myself, in which case I will talk to tensorflow team about it.      
Aside from that I hope you have played with tensorflow.rb and I hope you have liked it, Feel free to tell me about any other things that bother you or if you have any other queries. 

Thanks
